// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8fsPX7VkyNVDm9_r9G0eRFHRBtnqIfj8',
    appId: '1:1009266331586:web:2c96c2ca14c61e6916905b',
    messagingSenderId: '1009266331586',
    projectId: 'loginui-60394',
    authDomain: 'loginui-60394.firebaseapp.com',
    storageBucket: 'loginui-60394.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmTjnDf7DWd6PnafH0bWKwMA7YMFN3E3c',
    appId: '1:1009266331586:android:ed56a30a82a7e0cc16905b',
    messagingSenderId: '1009266331586',
    projectId: 'loginui-60394',
    storageBucket: 'loginui-60394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzHNif5Kg2xJd-23N2Ht8yns8NMOB7GA',
    appId: '1:1009266331586:ios:97169b2e8dc7a79d16905b',
    messagingSenderId: '1009266331586',
    projectId: 'loginui-60394',
    storageBucket: 'loginui-60394.appspot.com',
    iosClientId: '1009266331586-fb26io3ftp31jb6rif9m6jh75qm3ukde.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzHNif5Kg2xJd-23N2Ht8yns8NMOB7GA',
    appId: '1:1009266331586:ios:97169b2e8dc7a79d16905b',
    messagingSenderId: '1009266331586',
    projectId: 'loginui-60394',
    storageBucket: 'loginui-60394.appspot.com',
    iosClientId: '1009266331586-fb26io3ftp31jb6rif9m6jh75qm3ukde.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
